### ISSUE TITLE
Implement: Save Harvested Flags

### ISSUE THREAD

**Issue by duplexsystem** [RafearTheModder/PoachedBugsVR#29]
Can you implement flora respawn fix?

**Comment by RafearTheModder** [comment]
I have been very busy IRL, so sorry for slow response. I think I am finally clearing up some time to maybe start modding again, so I will take a look at doing this when I get the chance.

It looks like it needs another address reversed and added to the library still, as address ID 18843 does not exist in the VR version of the address library yet. I think it should be fairly simple to reverse and extremely simple to implement after that though. It's just a matter of finding the time.
